---
name: JailMate
version: 1.1.3
main: J0k3rrWild\JailMate\Main
api: 3.25.1
website: https://github.com/J0k3rrWild/
author: J0k3rrWild
commands:
 jail:
  description: Zatrzymuje gracza z rozgrywki
  permission: jail.command.jail
  usage: /jail <nick> | /unjail <nick> | /setjail confirm
 unjail:
  description: Gracz opuszcza przesluchanie
  permission: jail.command.unjail
  usage: /jail <nick> | /unjail <nick> | /setjail confirm
 setjail:
  description: Ustanawia miejsce aresztu
  permission: jail.command.setjail
  usage: /jail <nick> | /unjail <nick> | /setjail confirm
permissions:
  jail:
    default: op
    description: Daje uprawnienia do wszystkich komend aresztu
    children:
      jail.setjail:
        default: op
        description: Daje uprawnienia miejsca do ustanowienia aresztu
        children:
         jail.jail:
          default: op
          description: Daje uprawnienia do wypuszczania aresztu oraz aresztowania
          children:
            jail.bypass:
             default: op
             description: Daje veto w przypadku wymuszenia aresztowania

...
